services:
  privatebin:
    image: privatebin/unit-alpine:2.0.6
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: p.mv-angelbachtal.de,paste.mv-angelbachtal.de,privatebin.mv-angelbachtal.de
      LETSENCRYPT_HOST: p.mv-angelbachtal.de,paste.mv-angelbachtal.de,privatebin.mv-angelbachtal.de
      TZ: Europe/Berlin
    volumes:
      - data:/srv/data
      - ./conf.php:/srv/cfg/conf.php:ro
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  data:

